### ISSUE TITLE
Change release naming style.

### ISSUE THREAD

**Issue by mmatongo** [noirlinux/main#7]
The current style is non descriptive.
2021m could easily be mistaken for a 2021-march or 2021-may

New convention will be
`YEAR-MONTH-RELEASE`
i.e
`2021-AUG-1.tar.xz`

**Comment by mwenku** [comment]
I still haven't yet understood the naming convention, in the example you've given the naming of the releases should be `YEAR-MONTH-RELEASE`. Could you give an example of how the current release should have been named.

**Comment by mmatongo** [comment]
> Could you give an example of how the current release should have been named. 


`noir-chroot-2021-11-1.tar.xz`

In a situation where we have more than one release number we increment the release number. ie

`noir-chroot-2021-11-3.tar.xz`

**Comment by mwenku** [comment]
Thanks i understand
